ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';


DROP TABLE CENNIKPRODUCENTA;
DROP TABLE WYPOZYCZENIA;
DROP TABLE ZAMOWIENIA;
DROP TABLE PRODUCENT;
DROP TABLE cennikwypozyczalni;
DROP TABLE ASORTYMENT;
ALTER TABLE PRACOWNIK
    DROP CONSTRAINT FK__wypozyczalnia_Id;
DROP TABLE WYPOZYCZALNIA;
DROP TABLE PRACOWNIK;
DROP TABLE SPRZET;
DROP TABLE DANEOSOBOWE;
DROP TABLE LOKALIZACJA;


DROP VIEW ASORTYMENT_VIEW;
DROP VIEW CENNIK_PRODUCENTA_VIEW;
DROP VIEW PRACOWNICY_VIEW;
DROP VIEW PRODUCENT_VIEW;
DROP VIEW WYPOZYCZALNIA_VIEW;
DROP VIEW WYPOZYCZENIA_VIEW;
DROP VIEW ZAMOWIENIA_VIEW;
DROP VIEW CENNIKWYPOZYCZALNI_VIEW;



CREATE TABLE wypozyczalnia (
	wypozyczalniaId NUMBER(5) PRIMARY KEY,
	lokalizacjaId NUMBER(5) NOT NULL,
	pracownikId NUMBER(5) NOT NULL,
	nazwa VARCHAR2(30) NOT NULL,
	godzinaOtwarcia NUMBER(4,2),
	godzinaZamkniecia NUMBER(4,2)
)TABLESPACE USERS;

CREATE TABLE Pracownik (
	pracownikId NUMBER(5) PRIMARY KEY,
	daneId NUMBER(5) NOT NULL,
	wypozyczalniaId NUMBER(5) NOT NULL,
	login VARCHAR2(10) NOT NULL,
	haslo VARCHAR2(10) NOT NULL,
	dataZatrudnienia DATE
)TABLESPACE USERS;

CREATE TABLE Lokalizacja (
	lokalizacjaId NUMBER(5) PRIMARY KEY,
	kraj VARCHAR2(20) NOT NULL,
	miasto VARCHAR2(20) NOT NULL,
	ulica VARCHAR2(20) NOT NULL,
	budynek NUMBER NOT NULL,
	mieszkanie NUMBER,
	kodPocztowy NUMBER(5) NOT NULL
)TABLESPACE USERS;

CREATE TABLE Producent (
	producentId NUMBER(5) PRIMARY KEY,
	lokalizacjaId NUMBER(5) NOT NULL,
	nazwa VARCHAR2(30) NOT NULL,
	numerTelefonu NUMBER(11) NOT NULL,
	email VARCHAR2(30) NOT NULL
)TABLESPACE USERS;

CREATE TABLE CennikProducenta (
	cennikPId NUMBER(5) PRIMARY KEY,
	sprzetId NUMBER(5) NOT NULL,
	producentId NUMBER(5) NOT NULL,
	cenaMinimalna NUMBER (6,2),
	cenaMaksymalna NUMBER (6,2),
	czasDostawy NUMBER (4)
)TABLESPACE USERS;

CREATE TABLE CennikWypozyczalni (
	cennikWId NUMBER(5) PRIMARY KEY,
    wypozyczalniaId NUMBER(5) NOT NULL,
	sprzetId NUMBER(5) NOT NULL,
	cenaWypozyczenia NUMBER(4,2) NOT NULL,
	cenaUsterki1 NUMBER(6,2) NOT NULL,
	cenaUsterki2 NUMBER(6,2) NOT NULL,
	cenaUsterki3 NUMBER(6,2) NOT NULL
)TABLESPACE USERS;

CREATE TABLE Sprzet (
	sprzetId NUMBER(5)PRIMARY KEY,
	nazwa VARCHAR2(20) NOT NULL,
	rodzaj VARCHAR2(20),
	opis VARCHAR2(500)
)TABLESPACE USERS;

CREATE TABLE Asortyment (
	asortymentId NUMBER(5) PRIMARY KEY,
    wypozyczalniaId NUMBER(5) NOT NULL,
	sprzetId NUMBER(5) NOT NULL,
	stanWypozyczenia CHAR(1) NOT NULL,
	stanFizyczny VARCHAR2(30)
)TABLESPACE USERS;

CREATE TABLE DaneOsobowe (
	daneId NUMBER(5) PRIMARY KEY,
	imie VARCHAR2(15) NOT NULL,
	nazwisko VARCHAR2(30) NOT NULL,
	dataUrodzenia DATE,
	plec CHAR(1),
	numerTelefonu NUMBER(11) NOT NULL,
	email VARCHAR2(30)
)TABLESPACE USERS;

CREATE TABLE Zamowienia (
	zamowieniaId NUMBER(5) PRIMARY KEY,
	producentId NUMBER(5) NOT NULL,
	sprzetId NUMBER(5) NOT NULL,
	wypozyczalniaId NUMBER(5) NOT NULL,
	ilosc NUMBER(2) NOT NULL
)TABLESPACE USERS;

CREATE TABLE Wypozyczenia (
	wypozyczenieId NUMBER(5) PRIMARY KEY,
	wypozyczalniaId NUMBER(5) NOT NULL,
	daneId NUMBER(5) NOT NULL,
	czas NUMBER(2) NOT NULL,
	koszt NUMBER(6,2),
	data DATE
)TABLESPACE USERS;


ALTER TABLE Wypozyczalnia 
    ADD CONSTRAINT FK__lokalizacja_Id FOREIGN KEY  (lokalizacjaId) REFERENCES Lokalizacja(lokalizacjaId);

ALTER TABLE Pracownik 
    ADD (CONSTRAINT FK__dane_Id FOREIGN KEY (daneId) REFERENCES DaneOsobowe(daneId),
        CONSTRAINT FK__wypozyczalnia_Id FOREIGN KEY (wypozyczalniaId) REFERENCES Wypozyczalnia(wypozyczalniaId));
ALTER TABLE Producent 
    ADD CONSTRAINT FK__lokalizacjaP_Id FOREIGN KEY (lokalizacjaId) REFERENCES Lokalizacja(lokalizacjaId);

ALTER TABLE CennikProducenta 
	ADD (CONSTRAINT FK__sprzet_Id FOREIGN KEY (sprzetId) REFERENCES Sprzet(sprzetId),
        CONSTRAINT FK__producent_Id FOREIGN KEY (producentId) REFERENCES Producent(producentId),
        CONSTRAINT CK_cena_minimalna CHECK (cenaMinimalna > 0)
);

ALTER TABLE CennikWypozyczalni 
	ADD (CONSTRAINT FK__sprzetC_Id FOREIGN KEY  (sprzetId) REFERENCES Sprzet(sprzetId),
         CONSTRAINT FK__wypozyczalniaC_Id FOREIGN KEY  (wypozyczalniaId) REFERENCES Wypozyczalnia(wypozyczalniaId)
         );

ALTER TABLE Asortyment 
	ADD (CONSTRAINT FK__sprzetA_Id FOREIGN KEY  (sprzetId) REFERENCES Sprzet(sprzetId),
         CONSTRAINT FK__wypozyczalniaA_Id FOREIGN KEY  (wypozyczalniaId) REFERENCES WYPOZYCZALNIA(wypozyczalniaId));

ALTER TABLE DaneOsobowe
    ADD CONSTRAINT CK__plec CHECK(Plec IN ('M','F'));

ALTER TABLE Zamowienia 
	ADD (CONSTRAINT FK__producentZ_Id FOREIGN KEY (producentId) REFERENCES Producent(producentId),
        CONSTRAINT FK__sprzetZ_Id FOREIGN KEY (sprzetId) REFERENCES Sprzet(sprzetId),
        CONSTRAINT FK__wypzyczalniaZ_Id FOREIGN KEY (wypozyczalniaId) REFERENCES Wypozyczalnia(wypozyczalniaId),
        CONSTRAINT CK__ilosc CHECK (ilosc > 0)
);

ALTER TABLE Wypozyczenia 
	ADD( CONSTRAINT FK__wypozyczalniaW_Id FOREIGN KEY (wypozyczalniaId) REFERENCES Wypozyczalnia(wypozyczalniaId),
        CONSTRAINT FK__daneW_Id FOREIGN KEY (daneId) REFERENCES DaneOsobowe(daneId),
        CONSTRAINT CK_koszt CHECk (koszt > 0)
);

CREATE VIEW WYPOZYCZENIA_VIEW AS
SELECT w.wypozyczenieid as "ID",wy.nazwa as "Wypozyczalnia",d.imie as "Imie",d.nazwisko as "Nazwisko",d.numertelefonu as "Nr telefonu",w.czas as "Czas", w.koszt as "Koszt", w.data as "Data"
FROM WYPOZYCZENIA w
JOIN DANEOSOBOWE d ON (w.daneid = d.daneid)
JOIN WYPOZYCZALNIA wy ON (w.wypozyczalniaId = wy.wypozyczalniaid);

CREATE VIEW CENNIK_PRODUCENTA_VIEW AS
SELECT c.cennikPId as "ID",p.nazwa as "Producent", s.nazwa as "Sprz t",c.cenaminimalna as "Cena minimalna", c.cenamaksymalna as "Cena maksymalna",c.czasdostawy as "Czas dostawy"
FROM CENNIKPRODUCENTA c
JOIN producent p ON (c.producentid = p.producentid)
JOIN SPRZET s ON (c.sprzetid = s.sprzetid);

CREATE VIEW Pracownicy_view AS 
SELECT p.pracownikId as "Id",
    d.imie as "Imie",
    d.nazwisko as "Nazwisko",
    p.login as "Login",
    p.haslo as "Haslo",
    p.dataZatrudnienia as "Data zatrudnienia",
    w.nazwa as "Miejsce pracy"
FROM Pracownik p
JOIN DaneOsobowe d ON (d.daneId = p.daneId)
JOIN Wypozyczalnia w ON (w.pracownikId = p.pracownikId);

CREATE VIEW Zamowienia_view AS
SELECT z.zamowieniaId as "Id",
    p.nazwa as "Producenta",
    w.nazwa as "Wypozyczalnia",
    s.nazwa as "Sprzet",
    z.ilosc as "Ilosc"
FROM Zamowienia z
JOIN Producent p ON (p.producentId = z.producentId)
JOIN Sprzet s ON (z.sprzetId = s.sprzetId)
JOIN Wypozyczalnia w ON (w.wypozyczalniaId = z.wypozyczalniaId);

CREATE VIEW Wypozyczalnia_view AS
SELECT w.wypozyczalniaId as "Id",
    w.nazwa as "Nazwa",
    d.nazwisko as "Kierownik",
    w.godzinaOtwarcia as "Godzina otwarcia",
    w.godzinaZamkniecia as "Godzina zamkniecia",
    l.miasto + '/' + l.ulica + '/' + l.budynek as "Lokalizacja"
FROM Wypozyczalnia w 
JOIN Pracownik p ON (w.pracownikId = p.pracownikId)
JOIN DaneOsobowe d ON (d.daneId = p.daneID)
JOIN Lokalizacja l ON (l.lokalizacjaId = w.lokalizacjaId);

CREATE VIEW CennikWypozyczalni_view AS
SELECT c.cennikWId as "Id",
    w.nazwa as "Nazwa",
    s.nazwa as "Sprzet",
    c.cenaWypozyczenia as "Cena wypozyczenia",
    c.cenaUsterki1 as "Cena usterki 1",
    c.cenaUsterki2 as "Cena usterki 2",
    c.cenaUsterki3 as "Cena usterki 3"
FROM CennikWYPOZYCZALNI c 
JOIN Wypozyczalnia w ON (w.wypozyczalniaid = c.wypozyczalniaid)
JOIN Sprzet s ON (s.sprzetId = c.sprzetId);

CREATE VIEW Producent_view AS
SELECT p.producentId as "Id",
    p.nazwa as "Nazwa",
    p.numerTelefonu as "Numer telefonu",
    p.email as "Email",
    l.miasto + ' ' + l.ulica + ' ' + l.budynek as "Lokalizacja"
FROM Producent p
JOIN Lokalizacja l ON (p.lokalizacjaId = l.lokalizacjaId);

CREATE VIEW Asortyment_view AS
SELECT a.asortymentId as "Id",
    w.nazwa as "Nazwa",
    s.nazwa as "Sprzet",
    s.rodzaj as "Rodzaj",
    a.stanFizyczny as "Stan fizyczny",
    a.stanWypozyczenia as "Stan wypozyczenia"
FROM Asortyment a
JOIN Wypozyczalnia w ON (w.wypozyczalniaid = a.wypozyczalniaId)
JOIN Sprzet s ON (s.sprzetId = a.sprzetId);


INSERT ALL
    INTO DANEOSOBOWE (DANEID,IMIE,NAZWISKO,DATAURODZENIA,PLEC,NUMERTELEFONU,EMAIL) VALUES (1,'JAN','BERLO','18-12-2011','M',555333111,'JAS@GMAIL.PL')
    INTO DANEOSOBOWE (DANEID,IMIE,NAZWISKO,DATAURODZENIA,PLEC,NUMERTELEFONU,EMAIL) VALUES (2,'BARRACK','OBAMA','12-01-1963','M',555323121,'BARACZEK@GMAIL.PL')
    INTO DANEOSOBOWE (DANEID,IMIE,NAZWISKO,DATAURODZENIA,PLEC,NUMERTELEFONU,EMAIL) VALUES (3,'WOJCIECH','CEJROWSKI','17-03-1992','M',635333111,'BOSOPRZEZSWIAT@GMAIL.PL')
    INTO DANEOSOBOWE (DANEID,IMIE,NAZWISKO,DATAURODZENIA,PLEC,NUMERTELEFONU,EMAIL) VALUES (4,'MISZEL','OBAMA','17-01-2001','F',3217643131,'MISZEL@GMAIL.PL')
SELECT * FROM DUAL; 


INSERT ALL
    INTO SPRZET (SPRZETID,NAZWA,RODZAJ,OPIS) VALUES (1,'ROWER','LADOWY','DWUKOLOWY POJAZD NAPEDZANY SILA MIESNI')
    INTO SPRZET (SPRZETID,NAZWA,RODZAJ,OPIS) VALUES (2,'KAJAK','WODNY','NIEWIELKA LODZ REKREACYJNA')
    INTO SPRZET (SPRZETID,NAZWA,RODZAJ,OPIS) VALUES (3,'QUAD','LADOWY','CZTEROKOLOWY POJAZD NAPEDZANY MECHANICZNIE')
SELECT * FROM DUAL;

INSERT ALL
    INTO LOKALIZACJA (LOKALIZACJAID,KRAJ,MIASTO,ULICA,BUDYNEK,MIESZKANIE,KODPOCZTOWY) VALUES (1,'POLSKA','WROCLAW','MIKOLAJA REJA',14,11,43422)
    INTO LOKALIZACJA (LOKALIZACJAID,KRAJ,MIASTO,ULICA,BUDYNEK,MIESZKANIE,KODPOCZTOWY) VALUES (2,'POLSKA','SUPRASL','POSTERUNKOWA',1,12,93432)
SELECT * FROM DUAL;

INSERT ALL
    INTO PRODUCENT (PRODUCENTID,LOKALIZACJAID,NAZWA,NUMERTELEFONU,EMAIL) VALUES (1,2,'RUREX',532121532,'RUREX@WP.PL')
    INTO PRODUCENT (PRODUCENTID,LOKALIZACJAID,NAZWA,NUMERTELEFONU,EMAIL) VALUES (2,1,'DRUTEX',572128532,'DRUTEX@WP.PL')
SELECT * FROM DUAL;


INSERT ALL
    INTO CENNIKPRODUCENTA (CENNIKPID,SPRZETID,PRODUCENTID,CENAMINIMALNA,CENAMAKSYMALNA,CZASDOSTAWY) VALUES (1,1,1,400.50,600.00,12)
    INTO CENNIKPRODUCENTA (CENNIKPID,SPRZETID,PRODUCENTID,CENAMINIMALNA,CENAMAKSYMALNA,CZASDOSTAWY) VALUES (2,2,1,700.50,900.00,16)
    INTO CENNIKPRODUCENTA (CENNIKPID,SPRZETID,PRODUCENTID,CENAMINIMALNA,CENAMAKSYMALNA,CZASDOSTAWY) VALUES (3,1,2,350.90,700.00,20)
    INTO CENNIKPRODUCENTA (CENNIKPID,SPRZETID,PRODUCENTID,CENAMINIMALNA,CENAMAKSYMALNA,CZASDOSTAWY) VALUES (4,2,2,600.50,800.00,24)
SELECT * FROM DUAL;


INSERT ALL
    INTO WYPOZYCZALNIA (WYPOZYCZALNIAID,GODZINAOTWARCIA,GODZINAZAMKNIECIA,LOKALIZACJAID,NAZWA,PRACOWNIKID) VALUES (1,8.00,16.00,1,'WYPOL',1)
    INTO WYPOZYCZALNIA (WYPOZYCZALNIAID,GODZINAOTWARCIA,GODZINAZAMKNIECIA,LOKALIZACJAID,NAZWA,PRACOWNIKID) VALUES (2,8.00,16.00,2,'POZYCZALNIA',2)
SELECT * FROM DUAL;

INSERT ALL
    INTO ASORTYMENT(ASORTYMENTID,SPRZETID,STANWYPOZYCZENIA,STANFIZYCZNY,WYPOZYCZALNIAID) VALUES (1,1,'F','SPRAWNY',1)
    INTO ASORTYMENT(ASORTYMENTID,SPRZETID,STANWYPOZYCZENIA,STANFIZYCZNY,WYPOZYCZALNIAID) VALUES (2,1,'F','SPRAWNY',2)
    INTO ASORTYMENT(ASORTYMENTID,SPRZETID,STANWYPOZYCZENIA,STANFIZYCZNY,WYPOZYCZALNIAID) VALUES (3,2,'F','SPRAWNY',1)
    INTO ASORTYMENT(ASORTYMENTID,SPRZETID,STANWYPOZYCZENIA,STANFIZYCZNY,WYPOZYCZALNIAID) VALUES (4,2,'F','SPRAWNY',2)
SELECT * FROM DUAL;
    
INSERT ALL
    INTO PRACOWNIK (PRACOWNIKID,DANEID,WYPOZYCZALNIAID,LOGIN,HASLO,DATAZATRUDNIENIA) VALUES (1,1,1,'ADMIN','ADMIN','12-01-2022')
    INTO PRACOWNIK (PRACOWNIKID,DANEID,WYPOZYCZALNIAID,LOGIN,HASLO,DATAZATRUDNIENIA) VALUES (2,2,2,'LOGIN','HASLO','12-03-2021')
    INTO PRACOWNIK (PRACOWNIKID,DANEID,WYPOZYCZALNIAID,LOGIN,HASLO,DATAZATRUDNIENIA) VALUES (3,3,1,'SDSA','1234','17-05-2010')
SELECT * FROM DUAL;



INSERT ALL
    INTO ZAMOWIENIA (ZAMOWIENIAID,PRODUCENTID,SPRZETID,WYPOZYCZALNIAID,ILOSC) VALUES (1,1,1,1,10)
    INTO ZAMOWIENIA (ZAMOWIENIAID,PRODUCENTID,SPRZETID,WYPOZYCZALNIAID,ILOSC) VALUES (2,2,1,1,15)
    INTO ZAMOWIENIA (ZAMOWIENIAID,PRODUCENTID,SPRZETID,WYPOZYCZALNIAID,ILOSC) VALUES (3,1,2,2,5)
    INTO ZAMOWIENIA (ZAMOWIENIAID,PRODUCENTID,SPRZETID,WYPOZYCZALNIAID,ILOSC) VALUES (4,2,2,1,2)
SELECT * FROM DUAL;

INSERT ALL
    INTO WYPOZYCZENIA (WYPOZYCZENIEID,DANEID,CZAS,KOSZT,DATA,WYPOZYCZALNIAID) VALUES (1,4,3,23.23,'04-02-2022',1)
    INTO WYPOZYCZENIA (WYPOZYCZENIEID,DANEID,CZAS,KOSZT,DATA,WYPOZYCZALNIAID) VALUES (2,4,6,46.46,'05-09-2022',1)
SELECT * FROM DUAL;

INSERT ALL
    INTO CENNIKWYPOZYCZALNI(CENNIKWID,WYPOZYCZALNIAID,SPRZETID,CENAwYPOZYCZENia,CENAUSTERKI1,CENAUSTERKI2,CENAUSTERKI3) VALUES (1,1,1,10.50,25.0,60.0,200.0)
    INTO CENNIKWYPOZYCZALNI(CENNIKWID,WYPOZYCZALNIAID,SPRZETID,CENAwYPOZYCZENia,CENAUSTERKI1,CENAUSTERKI2,CENAUSTERKI3) VALUES (2,1,2,50.50,55.0,120.0,400.0)
SELECT * FROM DUAL;